name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "~/frontend"
          strip_components: 0
          rm: true

      - name: Deploy Frontend Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/frontend
            sudo docker build --build-arg NEXT_PUBLIC_API_URL=https://api.cambridgesuccesscentre.com -t lms-frontend .
            sudo docker stop frontend-container || true
            sudo docker rm frontend-container || true
            sudo docker run -d --name frontend-container -p 3000:3000 lms-frontend
